In [9]:
import numpy as np
a=np.arange(1,13).reshape(3,4)
print(a)
# First row
a[0,:]
# Last row
a[-1,:]
# Second column
a[:,1]
# Last column
a[:,-1]
# Middle two columns
a[:, 1:3]
# Every other column
a[:, ::2]
# Bottom-right element
a[-1,-1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


np.int64(12)

In [19]:
b=np.array([[1,2,3],
              [4,5,6]])
# Sum by column
print(np.sum(b, axis = 0))
# Sum by row
print(np.sum(b, axis = 1))
# Sum of all elements
print(np.sum(b))
# Maximum
print(np.max(b))
# Minimum 
print(np.min(b))


[5 7 9]
[ 6 15]
21
6
1
