**  LINEAR ALGEBRA **

In [2]:
import numpy as np
a= np.ones((2,3))
print(a)
b= np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [3]:
#Find the determinant
c= np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [4]:
#SVD
np.linalg.svd(c)

SVDResult(U=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), S=array([1., 1., 1.]), Vh=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))

In [5]:
#Trace
np.trace(c)

np.float64(3.0)

In [8]:
#Eigenvalues
np.linalg.eig(c)

EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))

In [9]:
#Matrix norm
np.linalg.norm(c)

np.float64(1.7320508075688772)

In [10]:
#Inverse
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###STATISTICS

In [11]:
arr = np.array([[5,2,4],[6,9,1]])
arr

array([[5, 2, 4],
       [6, 9, 1]])

In [18]:
#MIN
np.min(arr, axis = 1)

array([2, 1])

In [16]:
#MAX
np.max(arr, axis = 0)

array([6, 9, 4])

**Notes** 
+ axis = 0 column
+ axis = 1 row

In [19]:
#SUM
np.sum(arr, axis = 0)

array([11, 11,  5])