# BOOLEAN COMPARISON

In [13]:
import numpy as np
a = np.array([[6,4,9],[2,5,7]])

In [14]:
# Boolean mask
a>5

array([[ True, False,  True],
       [False, False,  True]])

In [15]:
# Use mask to filter
a[a>5]
a[a!=5]

array([6, 4, 9, 2, 7])

##### For multiple conditions: 
###### AND &
###### OR |
###### NOT ~

In [16]:
a[(a>3) & (a<7)]

array([6, 4, 5])

###### np.where

In [17]:
# Find position
a= np.array([[9,4,7],[2,6,3]])
np.where(a>4) #1st array returns row indices, 2nd returns column indices

(array([0, 0, 1]), array([0, 2, 1]))

In [18]:
# Conditional replacement
b= np.where(a>5, 100, 0) #a>5 replace with 100, a<=5 replace with 0
print(b)

[[100   0 100]
 [  0 100   0]]


##### Note: np.where does not adjust the original array, but an alternative

In [24]:
# Find position of extreme value
np.argmax(a)
np.argmin(a, axis = 1)

array([1, 0])