# ARRAY MANIPULATION

### 1. reshape()

In [1]:
import numpy as np
a= np.arange(1,13).reshape(3,4)

### 2. transpose() - swap rows and columns

In [2]:
a= np.array([[1,2,3],[5,6,7]])
a.T #C1
np.transpose(a) #C2

array([[1, 5],
       [2, 6],
       [3, 7]])

### 3. flatten()

In [3]:
x=a.flatten()

### 4. ravel()

In [4]:
y=a.ravel()

### 5. Practice

In [5]:
# Create a 3×3 matrix with values ranging from 0 to 8.
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# COMBINING ARRAYS
### 1. np.concatenate()

In [6]:
a = np.array([[2,4],[6,8]])
b = np.array([[3,5],[7,9]])
np.concatenate((a,b), axis = 0) #or no axis, same for 2*2 arr


array([[2, 4],
       [6, 8],
       [3, 5],
       [7, 9]])

In [7]:
np.concatenate((a,b), axis = 1)

array([[2, 4, 3, 5],
       [6, 8, 7, 9]])

axis = 0: Adding rows-    (2,2) + (2,2) = (4,2)
axis = 1: Adding columns- (2,2) +(2,2) = (2,4)

### 2. np.vstack()
vstack = vertical stack

In [8]:
np.vstack((a,b)) #convenient version of np.concatenate((a,b), axis = 0)

array([[2, 4],
       [6, 8],
       [3, 5],
       [7, 9]])

### 3. np.hstack()
hstack = horizontal stack

In [9]:
np.hstack((a,b)) #convenient version of np.concatenate((a,b), axis = 1)

array([[2, 4, 3, 5],
       [6, 8, 7, 9]])

### 4. np.split()

In [10]:
a = np.arange(1,7)
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [11]:
b= np.arange(1,13).reshape(3,4)
np.split(b, 2, axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

### 5. Practice

In [12]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

In [14]:
# Exercise 1: Use concatenate() to produce:
#[[1 2]
# [3 4]
# [5 6]
# [7 8]]
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
# Exercise 2
# Use concatenate() to produce:
# [[1 2 5 6]
#  [3 4 7 8]]
np.concatenate((a,b), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [16]:
# Exercise 3
# Produce the first result using vstack().
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
# Exercise 4
# Produce the second result using hstack().
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [19]:
# Exercise 5: split it into two arrays, each containing 2 columns.
c = np.arange(1, 13).reshape(3, 4)
np.split(c, 2, axis = 1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

# tile()
##### Repeat an array/pattern

In [22]:

# 1D
a = np.array([1,2,3])
np.tile(a,2)

array([1, 2, 3, 1, 2, 3])

In [ ]:
# 2D
a = np.array([[1,2,3],[2,3,4]])
np.tile(a,(2,3))
# rows repeat
# columns repeat

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4, 2, 3, 4],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [2, 3, 4, 2, 3, 4, 2, 3, 4]])

#### Practice

In [24]:
# 1. Create: [1 2 3 1 2 3 1 2 3] using np.tile().
a=np.array([1,2,3])
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
# 2. Create this:
# [[0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]]
b = np.array([[0,1,0,1,0,1,0,1], [1,0,1,0,1,0,1,0]])
np.tile(b, (4, 1))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [30]:
# 3. Create a 5×5 matrix with row values ranging from 0 to 4.
c = np.array([0,1,2,3,4])
np.tile(c,(5,1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

# BROADCASTING

In [31]:
a = np.array([1,6,7])
a+10

array([11, 16, 17])

In [32]:
a= np.array([[1,2,3], [4,5,6]])
b = np.array([10,20,30])
a+b

array([[11, 22, 33],
       [14, 25, 36]])

#### When does it work?
2 dimensions are compatible if:
+ they are equal
+ one of them is 1
+ one array doesnt have that dimension
Ex1: (2,3) + (3) --> compatible (3=3)
Ex2: (2,3) + (2) --> incompatible (2!=3- compare from the right)

# MEAN (average)

In [ ]:
scores = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [95, 90, 100]
])
np.mean(scores, axis = 0)
np.mean(scores, axis = 1)

array([78.33333333, 81.66666667, 88.33333333])

# MEDIAN (The middle value after sorting)
Median is less affected by extreme outliers

In [34]:
a = np.array([1,2,3,100])
np.median(a)

np.float64(2.5)

# STANDARD DEVIATION np.std()
measure how spread out the data is

In [ ]:
a = np.array([1,2,3,4,5])
np.std(a)

Meaning:
+ small std: values are close together
+ large std: values are more spread out

# VARIANCE np.var()
= standard deviation squared

# keepdims

In [36]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
row_mean = np.mean(a, axis=1, keepdims = True)
a - row_mean

array([[-10.,   0.,  10.],
       [-10.,   0.,  10.]])

it is useful in broadcasting 'cause it keeps the reduced dimension as size 1