### FROM 100 NUMPY EXERCISES 
https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [3]:
#numpy version
print(np.__version__)
#numpy configuration
np.show_config()

2.3.5
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35219",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.1",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35219",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tire4up4/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib d

c:\Users\Jane\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


3. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.zeros(10, dtype = np.int32)

4. How to find the memory size of any array (★☆☆)

In [5]:
print(a.nbytes)

40


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
python -m pydoc numpy.add

SyntaxError: invalid syntax (3906867247.py, line 1)

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a = np.array([1,2,0,0,4,0])
indices = np.nonzero(a)
print(indices)

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [9]:
np.random.rand(3,3,3)

array([[[0.39629458, 0.65824221, 0.05287261],
        [0.53329141, 0.17829156, 0.46961083],
        [0.26054168, 0.83340213, 0.25167174]],

       [[0.62834721, 0.42582315, 0.58558285],
        [0.57716003, 0.90932335, 0.25378858],
        [0.8443555 , 0.20508177, 0.55288136]],

       [[0.31669339, 0.6150963 , 0.10413802],
        [0.18760556, 0.02462286, 0.55297648],
        [0.66144061, 0.2793009 , 0.40107699]]])

In [ ]:
13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [10]:
a = np.random.rand(10,10)
print(a)
max = np.max(a)
print(max)
min = np.min(a)
print(min)

[[0.28521953 0.80620084 0.78292444 0.29653678 0.96165774 0.07811122
  0.72565106 0.68574333 0.00255271 0.19624719]
 [0.21805281 0.15257145 0.13498861 0.44980187 0.63008189 0.67419037
  0.72293968 0.58117281 0.04753307 0.62079494]
 [0.51603402 0.81164436 0.12582258 0.93484753 0.55149037 0.86981449
  0.38754719 0.83792557 0.69069689 0.41136265]
 [0.91619992 0.77868612 0.37684566 0.11513896 0.94531265 0.07853864
  0.33436981 0.72038644 0.84482483 0.50560856]
 [0.77885757 0.85722424 0.09259669 0.11470215 0.72468259 0.4665046
  0.91123254 0.45386776 0.51186034 0.99747186]
 [0.76907563 0.36396463 0.29215886 0.22161791 0.74004791 0.19069752
  0.63999376 0.26001782 0.09180858 0.45615964]
 [0.50316404 0.74820786 0.50660223 0.49694305 0.43297063 0.17473053
  0.39797776 0.82715266 0.49538744 0.20769544]
 [0.64454559 0.11566309 0.90119163 0.91039427 0.64982045 0.61125609
  0.07299689 0.07095197 0.01577315 0.68337976]
 [0.30816148 0.73445573 0.47621862 0.37049279 0.78800912 0.85251703
  0.83362429 

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [11]:
a = np.random.rand(30)
print(a)
mean = np.mean(a)
print(mean)

[0.17522609 0.37171634 0.05776779 0.54478839 0.31766271 0.98625275
 0.72169552 0.09254126 0.0800782  0.07836634 0.92107519 0.90985018
 0.28097762 0.18610549 0.38623713 0.134743   0.09693304 0.55568085
 0.50263851 0.40553255 0.82637516 0.76510586 0.86143007 0.6236472
 0.7417276  0.34500587 0.26909728 0.34996848 0.67367043 0.05345959]
0.4438452157959694


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [13]:
a = np.ones((4,3))
a[1,1] = 0
a[2,1] = 0
print(a)


[[1. 1. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
array = np.ones((3,3))
bordered_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)