##DAY 2: INITIALIZING DIFFERENT TYPES OF ARRAYS

In [1]:
#All 0s matrix
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
#All 1s matrix
np.ones((3,2,2), dtype=np.int32)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [3]:
#Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [4]:
a = np.array([[1,2,3], [4,5,6]]) 

In [5]:
#Any other number (full-like)
np.full_like(a, 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [8]:
#Random decimal number
np.random.rand(4,2)

array([[0.41846918, 0.42001348],
       [0.77328098, 0.5096113 ],
       [0.75125842, 0.88299596],
       [0.16023667, 0.30667314]])

In [9]:
#Random decimal number based on a shape
np.random.random_sample(a.shape)

array([[0.39096262, 0.46507651, 0.17975384],
       [0.3054417 , 0.99908734, 0.32431496]])

In [ ]:
#Random integer numbers
np.random.randint(7, size=(2,2))
np.random.randint(-2,6,(3,2))
# (start, stop (exclusive), size)

array([[ 1,  5],
       [ 2, -2],
       [-2,  3]], dtype=int32)

In [11]:
#The Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
#Repeat an array
arr = np.array([[1,2,3], [2,3,4]])
r1 = np.repeat(arr,2,axis =1)
print(r1)

[[1 1 2 2 3 3]
 [2 2 3 3 4 4]]


In [25]:
#Print out a specific matrix
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


*Be careful when copying array!*

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
# if 
# b=a
# b[0] = 100
# a= [100,2,3] = b


[1 2 3]


**MATHEMATICS**

In [27]:
a= np.array([2,6,4,8])
print(a)

[2 6 4 8]


In [28]:
a+2

array([ 4,  8,  6, 10])

In [29]:
a/2

array([1., 3., 2., 4.])

In [33]:
b=np.array([1,2,3,4])
print(b)

[1 2 3 4]


In [34]:
a*b

array([ 2, 12, 12, 32])

In [35]:
#Take the sin
np.sin(a)

array([ 0.90929743, -0.2794155 , -0.7568025 ,  0.98935825])