In [7]:
import numpy as np
#1 Padding- Add a border of 0s around it
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.pad(a, pad_width=1, mode = "constant", constant_values=0)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
#2 Negate every element between 3 and 8 inclusive.
a = np.array([1, 4, 6, 9, 3, 8, 10])
np.where((a>=3)&(a<=8), a*-1, a) #1
a[(a>=3)&(a<=8)] *= -1 #2
print(a)

[ 1 -4 -6  9 -3 -8 10]


In [10]:
#3 Find the values that appear in both arrays.
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
np.intersect1d(a,b)

array([3, 4, 5])

In [22]:
#4 Create a 5×5 matrix with:
# 0 0 0 0 0
# 1 0 0 0 0
# 2 1 0 0 0
# 3 2 1 0 0
# 4 3 2 1 0
a = (np.diag([1,1,1,1], k=-1) + np.diag([2,2,2], k=-2) + np.diag([3,3], k=-3) + np.diag([4], k=-4))
print(a)
a = np.zeros((5,5))
for i in range(1,5):
    a += np.diag([i]*(5-i), k=-i)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [2 1 0 0 0]
 [3 2 1 0 0]
 [4 3 2 1 0]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]]


In [28]:
#5 Create 
# [[0 1 2 3 4]
#  [0 1 2 3 4]
#  [0 1 2 3 4]
#  [0 1 2 3 4]
#  [0 1 2 3 4]]
a= np.array([0,1,2,3,4])
np.tile(a,(6,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [29]:
#6 Subtract the mean of each row from every element in that row.
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a-np.mean(a, axis =1, keepdims=True)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])