# VECTORIZATION
Instead of telling Python what to do with each element, you tell Numpy the operation for the whole array
### 1. Example (double the array):

In [14]:
# Python
numbers = [1,2,3,4,5]
result = []
for num in numbers:
    result.append(num*2)
print(result)
# numpy
import numpy as np
a = np.array([1,2,3,4,5])
a*2


[2, 4, 6, 8, 10]


array([ 2,  4,  6,  8, 10])

### 2. Numpy functions

In [15]:
np.sqrt(a) # square root
np.abs(a) # |a|
np.exp(a) # e^a
np.log(a) # ln(a)
np.log2(a) # log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

### 3. Practice

In [16]:
#1 Square every number
a = np.array([1, 2, 3, 4, 5])
a**2

array([ 1,  4,  9, 16, 25])

In [17]:
#2 Add 10 to every number
a = np.array([5, 10, 15, 20])
a+10

array([15, 20, 25, 30])

In [18]:
#3 Find the absolute values
a = np.array([-5, -2, 0, 3, 8])
np.abs(a)

array([5, 2, 0, 3, 8])

In [19]:
#4 Find the square root of every number
a = np.array([1, 4, 9, 16, 25])
np.sqrt(a)

array([1., 2., 3., 4., 5.])

In [20]:
#5 Create an array that tells you whether each student passed. The passing score is 70.
scores = np.array([65, 72, 81, 90, 55])
scores>=70

array([False,  True,  True,  True, False])

In [21]:
#6 Everything gets a 10% discount. Calculate the discounted prices without a loop.
prices = np.array([100, 200, 300, 400])
result = prices*0.9
print(result)

[ 90. 180. 270. 360.]


In [22]:
#7 Add 5 points to every score, then find the new average for each subject.
scores = np.array([
    [60, 80, 90],
    [70, 75, 85],
    [95, 60, 70]
])
result = scores+5
result = np.mean(result, axis = 0)
print(result)

[80.         76.66666667 86.66666667]


# RANDOM
### 1. np.random.rand()

In [23]:
# generates random float number btw 0 and 1
np.random.rand()

0.9237810669000006

In [24]:
# multiple numbers
np.random.rand(5)

array([0.72096531, 0.41110578, 0.19532433, 0.55103947, 0.59553662])

In [25]:
# matrix
np.random.rand(3,2)

array([[0.80950052, 0.79365962],
       [0.72858173, 0.75187422],
       [0.03685504, 0.87367795]])

### 2. np.random.randint()
generates random integers

In [ ]:
#one integer
np.random.randint(1,10)

1

In [28]:
#vector
np.random.randint(1,10,size=(3,2))

array([[6, 6],
       [9, 4],
       [7, 7]], dtype=int32)

### 4. np.random.seed()
will always give the same sequence after setting that seed.

In [31]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


### 5. Practice

In [32]:
# Exercise 1 — Create a random vector of 10 floats between 0 and 1.
np.random.rand(10)

array([0.59865848, 0.15601864, 0.15599452, 0.05808361, 0.86617615,
       0.60111501, 0.70807258, 0.02058449, 0.96990985, 0.83244264])

In [34]:
# Exercise 2- Create a 3×4 matrix of random floats between 0 and 1.
np.random.rand(3,4)

array([[0.21233911, 0.18182497, 0.18340451, 0.30424224],
       [0.52475643, 0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [35]:
# Exercise 3 - Create a vector of 10 random integers from 1 to 100.
np.random.randint(1,101, 10)

array([47, 62, 51, 55, 64,  3, 51,  7, 21, 73], dtype=int32)

In [36]:
# Exercise 4 - Create a 10×10 array with random values and find: minimum, maximum
a= np.random.rand(10,10)
print(a)
print(np.max(a))
print(np.min(a))

[[0.06505159 0.94888554 0.96563203 0.80839735 0.30461377 0.09767211
  0.68423303 0.44015249 0.12203823 0.49517691]
 [0.03438852 0.9093204  0.25877998 0.66252228 0.31171108 0.52006802
  0.54671028 0.18485446 0.96958463 0.77513282]
 [0.93949894 0.89482735 0.59789998 0.92187424 0.0884925  0.19598286
  0.04522729 0.32533033 0.38867729 0.27134903]
 [0.82873751 0.35675333 0.28093451 0.54269608 0.14092422 0.80219698
  0.07455064 0.98688694 0.77224477 0.19871568]
 [0.00552212 0.81546143 0.70685734 0.72900717 0.77127035 0.07404465
  0.35846573 0.11586906 0.86310343 0.62329813]
 [0.33089802 0.06355835 0.31098232 0.32518332 0.72960618 0.63755747
  0.88721274 0.47221493 0.11959425 0.71324479]
 [0.76078505 0.5612772  0.77096718 0.4937956  0.52273283 0.42754102
  0.02541913 0.10789143 0.03142919 0.63641041]
 [0.31435598 0.50857069 0.90756647 0.24929223 0.41038292 0.75555114
  0.22879817 0.07697991 0.28975145 0.16122129]
 [0.92969765 0.80812038 0.63340376 0.87146059 0.80367208 0.18657006
  0.892559  

In [37]:
# Exercise 5 - Create a random vector of size 30 and find its mean.
a= np.random.rand(30)
print(np.mean(a))

0.48222820048631915


In [38]:
# Exercise 6 - Create a random vector of size 10 and sort it.
a= np.random.rand(10)
np.sort(a)

array([0.01658783, 0.04077514, 0.09028977, 0.18651851, 0.32078006,
       0.53577468, 0.59089294, 0.63352971, 0.67756436, 0.8353025 ])

In [ ]:
# Exercise 7 - Create a random vector of size 10. Then replace its maximum value with 0.
a = np.random.rand(10)
a[np.argmax(a)] = 0