In [2]:
import numpy as np
#1
A = np.array([1,2,3,4])
B= np.array([3,4,5,6])
((A+B)*(-A/2))

array([ -2.,  -6., -12., -20.])

In [ ]:
#2 Make a read-only array
a = np.array([1,2,3])
a.flags.writeable = False
# unlock
a.flags.writeable = True

In [10]:
# 2.1 Make it read-only
a = np.arange(5)
a.flags.writeable = False

In [11]:
#3 enumerate() & np.ndenumerate()
# enumerate() for 1d array only
numbers = [10,20,30]
for i, value in enumerate(numbers):
    print(i, value)
# np.ndenumerate for n dimensional arrays
a = np.array([
    [10,20],
    [30,40]
])
for index, value in np.ndenumerate(a):
    print(index, value)


0 10
1 20
2 30
(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


In [13]:
#3.1 Print index, value
a = np.array([
    [5, 8],
    [2, 9]
])
for index, value in np.ndenumerate(a):
    print(index,value)

(0, 0) 5
(0, 1) 8
(1, 0) 2
(1, 1) 9


In [14]:
#3.2 Find and print (index,value) with value > 5
a = np.array([
    [5, 8],
    [2, 9]
])
for index, value in np.ndenumerate(a):
    if value>5:
        print(index,value)

(0, 1) 8
(1, 1) 9


In [5]:
#4 Sort rows according to the 2nd columnm
a = np.array([
    [3, 8, 1],
    [5, 2, 9],
    [4, 7, 6]
])
order = np.argsort(a[:,1]) #sort the 2nd column
a[[order]] #fancy indexing 

array([[[5, 2, 9],
        [4, 7, 6],
        [3, 8, 1]]])

Pattern: 
order = np.argsort(a[row,col])
a[[order]]

In [ ]:
#4.1 Sort rows theo column 1
a = np.array([
    [10, 5],
    [20, 2],
    [30, 8],
    [40, 1]
])
order = np.argsort(a[:,0])
a[[order]]

array([[[10,  5],
        [20,  2],
        [30,  8],
        [40,  1]]])

In [8]:
#4.2 Sort rows theo col 1
a = np.array([
    [1, 90, 5],
    [2, 70, 8],
    [3, 80, 2]
])
order = np.argsort(a[:,0])
a[[order]]

array([[[ 1, 90,  5],
        [ 2, 70,  8],
        [ 3, 80,  2]]])

In [ ]:
#5 Subtract mean of each row
a = np.array([
    [3, 8, 1],
    [5, 2, 9],
    [4, 7, 6]
])
mean=np.mean(a, axis = 0, keepdims=True)
a-mean

array([[-1.        ,  2.33333333, -4.33333333],
       [ 1.        , -3.66666667,  3.66666667],
       [ 0.        ,  1.33333333,  0.66666667]])

In [ ]:
#6 Check if there is any full zero column
a = np.array([
    [1, 0, 3],
    [2, 0, 4],
    [5, 0, 6]
])
np.all(a==0, axis = 0)


array([False,  True, False])

Pattern:
+ np.all() AND
np.all(condition, axis (if any))
Ex: np.all(age>5)
Ex: np.all(a == b)
+ np.any() OR



In [17]:
#6.1 Find columns that are full-zero
a = np.array([
    [0, 1, 0],
    [0, 2, 0],
    [0, 3, 0]
])
np.all(a==0, axis = 0)

array([ True, False,  True])

In [19]:
#6.2 Find columns/rows that are full-zeros
a = np.array([
    [1, 0, 3],
    [0, 0, 0],
    [2, 0, 5]
])
np.all(a==0, axis = 0)
np.all(a==0, axis = 1)

array([False,  True, False])

In [20]:
#7 Sum of many axis
a = np.ones((2,3,4,5))
# Sum of the last 2 axis
np.sum(a, axis = (2,3))


array([[20., 20., 20.],
       [20., 20., 20.]])

In [24]:
#7.1 sum 2 last axis
a = np.arange(120).reshape(2,3,4,5)
a = np.sum(a, axis = (2,3))
a.shape

(2, 3)

In [ ]:
#8 Broadcasting shape (5,5,3) x (5,5)
A.shape == (5,5,3)
B.shape == (5,5)
# Solution: Add a dimension to B
B[:,:, np.newaxis]
A*B[:,:, np.newaxis]

In [26]:
#9 Find the nearest value to 34
a = np.array([10, 20, 30, 40, 50])
x = 34
a[np.argmin(np.abs(a-x))]

np.int64(30)

In [28]:
#10 Most frequent value
a = np.array([1,2,2,3,3,3,4,4])
values, counts = np.unique(a, return_counts = True)
values[np.argmax(counts)]

np.int64(3)

In [29]:
#10.1 Find the most frequent value
a = np.array([5,1,5,2,5,3,2,1,5])
values, counts = np.unique(a, return_counts = True)
values[np.argmax(counts)]

np.int64(5)

np.unique(a) clear duplicates and sort ascending
#### COUNT
score, number = np.unique(assessment, return_counts = True)
score return ascending assessment list with no duplicates
while number return numbers of people reaching relative score
#### RETURN THE FIRST POSITION
score, first_index = np.unique(assessment, return_index = True)