In [ ]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])

In [4]:
# 17. Add a border of 0s around an existing array
array = np.pad(array, pad_width=1, mode = 'constant', constant_values= 0)
print(array) 

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]


In [ ]:
# 18. 5×5 matrix with 1,2,3,4 below diagonal


In [ ]:
# 8×8 checkerboard

In [ ]:
# 8×8 checkerboard using np.tile

In [ ]:
# Multiply 5×3 × 3×2 matrices

In [ ]:
# Negate elements between 3 and 8 in place

In [ ]:
# Find common values between two arrays

In [ ]:
# Normalize a 5×5 random matrix

In [ ]:
# (6,7,8) array: index of 100th element

In [ ]:
# What are the results of the NaN expressions?