**  LINEAR ALGEBRA **

In [1]:
import numpy as np
a= np.ones((2,3))
print(a)
b= np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#Find the determinant
c= np.array()