###### PRACTICE FOR BOOLEAN MASKING

In [14]:
import numpy as np
a= np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
#1 Take out numbers > 7
a[a>7]

array([ 8,  9, 10, 11, 12])

In [16]:
#2 Take out all even numbers
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [17]:
#3 Take out all numbers belong to [4,9]
a[(a>=4) & (a<=9)]

array([4, 5, 6, 7, 8, 9])

In [ ]:
#4 Replace all numbers that > 8 with 100
#C1
b = np.where(a>8, 100, a) 
print(b)

[[  0   0   0   0]
 [  0   0   0   0]
 [100 100 100 100]]


###### /Keep the other values by 'a'/

In [ ]:
#C2
a[a>8] = 100
print(a)

In [19]:
#5 Find indexes of all numbers that are >8 using np.where()
np.where(a>8)

(array([2, 2, 2, 2]), array([0, 1, 2, 3]))

In [28]:
#6 Find indices of non-zero elements from given list
arr = np.array([1,2,0,0,4,0])
np.where(arr!=0)

(array([0, 1, 4]),)

In [31]:
#7 Given an 1D array, negate all elements which are between 3 and 8 in place
arr[(arr>=3) & (arr<=8)] *= -1
print((arr))

[ 1  2  0  0 -4  0]


In [32]:
#8 How to find common values between 2 arrays?
a= np.array([1,2,3,6])
b= np.array([3,4,5,6])
np.intersect1d(a,b)

array([3, 6])

In [33]:
#9 Create random vector of size 10 and replace maximum value by 0
array = np.random.randint(1,100, size = 10)
array[np.argmax(array)] = 0
print(array)

[53 59  0  3 12 34 67 15 62 49]
