##NumPy Day 1
#Topics
- ndarray
- shape
- dtype
- indexing
- slicing

In [1]:
import numpy as np 
a = np.array([2,3,4])
b = np.array([1,3,2])
c = np.array([[2.3, 5.6, 6.2], [7.8, 9.0, 2.1]])
d = np.array([[[[1,2], [2,3], [4,5]]]])
print(a)
print(c)
print(d)
print (a*b)

[2 3 4]
[[2.3 5.6 6.2]
 [7.8 9.  2.1]]
[[[[1 2]
   [2 3]
   [4 5]]]]
[2 9 8]


**Observation**: NumPy arrays have a single data type. Unlike Python lists which can mix integers, strings and floats, NumPy forces a uniformtype. This memory contiguity is the reason NumPy operations are faster than lists.

In [ ]:
#Get dimension
d.ndim

**Observation**: Number of dimensions = number of opening brackets

In [ ]:
#Get shape
d.shape

About Shape (a,) a: elements 
            (a,b) a: rows b: columns

In [ ]:
#Get dtype (Data Type)
print(a.dtype)

# Forcing a specific data type
e = np.array([6,7,8], dtype = np.int32)
print(e.dtype)

In [ ]:

#Get item size = size of one element. Note that size: number of memory used
a.itemsize

In [ ]:

#Get number of elements
d.size

In [ ]:

#Get totalsize- total number of memories used by an array
a.nbytes

**Note**: 
bool_: 1 byte 
int8: 1 byte 
int16: 2 bytes 
int32 = float32: 4 bytes 
int64 = float64: 8 bytes

**SLICING**

In [ ]:

a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)

In [ ]:

#Get a specific element [row, col]
print(a[1,2])
#OR
print(a[1,-3])

In [ ]:
#Get a row
a[0, :]
# OR
print(a[0,:])

In [ ]:
#Get a column
a[:, 2]

In [ ]:

#Get patterned elements [startIndex: endIndex: stepSize]
a[1, 0:2:2]
a[:, ::2]

**Note**: Slicing is half-open [start,end)

In [ ]:
#Change an element
a[0,3] = 100
print(a)

In [ ]:

#Change a column uniformly
a[:,3] = 120
print(a)
#Change a row
a[1,:]= 200

In [ ]:

#Change a row/column in sequence
a[:, 3] = [2,4]
print(a)

In [ ]:
j= np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(j)
print(j[1,1,0]) #get an element
print(j[1,:,:])