In [15]:
import numpy as np
#1 Padding- Add a border of 0s around it
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.pad(a, pad_width=1, mode = "constant", constant_values=0)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 0, 0, 0, 0]])

In [16]:
#2 Negate every element between 3 and 8 inclusive.
a = np.array([1, 4, 6, 9, 3, 8, 10])
np.where((a>=3)&(a<=8), a*-1, a) #1
a[(a>=3)&(a<=8)] *= -1 #2
print(a)

[ 1 -4 -6  9 -3 -8 10]


In [17]:
#3 Find the values that appear in both arrays.
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
np.intersect1d(a,b)

array([3, 4, 5])

In [18]:
#4 Create a 5×5 matrix with:
# 0 0 0 0 0
# 1 0 0 0 0
# 2 1 0 0 0
# 3 2 1 0 0
# 4 3 2 1 0
a = (np.diag([1,1,1,1], k=-1) + np.diag([2,2,2], k=-2) + np.diag([3,3], k=-3) + np.diag([4], k=-4))
print(a)
a = np.zeros((5,5))
for i in range(1,5):
    a += np.diag([i]*(5-i), k=-i)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [2 1 0 0 0]
 [3 2 1 0 0]
 [4 3 2 1 0]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]]


In [19]:
#5 Create 
# [[0 1 2 3 4]
#  [0 1 2 3 4]
#  [0 1 2 3 4]
#  [0 1 2 3 4]
#  [0 1 2 3 4]]
a= np.array([0,1,2,3,4])
np.tile(a,(6,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [20]:
#6 Subtract the mean of each row from every element in that row.
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a-np.mean(a, axis =1, keepdims=True)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [21]:
#7 Create a vector [10 11 12 13 ... 49]
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [35]:
#8 Reverse a vector
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
#9 Find the indices of all non-zero elements.
a = np.array([1, 2, 0, 0, 4, 0])
np.where(a!=0)

(array([0, 1, 4]),)

In [38]:
#10 Create a 5×5 matrix with: 1 on the border, 0 inside
a = np.ones((5,5))
b = np.zeros((3,3))
a[1:-1:,1:-1] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
#11 Create an 8×8 checkerboard using 0 and 1.
a = np.array([0,1,0,1,0,1,0,1])
b = np.array([1,0,1,0,1,0,1,0])
np.tile([a,b],(4,1)) #c1
pattern = np.array([a,b]) #c2
np.tile(pattern, (4,1))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [46]:
#12 Normalize it so that: minimum becomes 0- maximum becomes 1
a = np.random.rand(5,5)
normalized = (a - np.min(a)) / (np.max(a) - np.min(a))
print(normalized)

[[0.6360908  0.12372468 0.09287341 0.80787061 0.91657716]
 [0.93080548 0.78641735 0.20700217 1.         0.71141084]
 [0.78403369 0.2215764  0.92343465 0.69691898 0.73285962]
 [0.0579257  0.67038549 0.59114496 0.         0.84776915]
 [0.448281   0.17975685 0.32085234 0.42701597 0.2483336 ]]


In [27]:
#13 Negate every number between 3 and 8 inclusive, in place.
a = np.array([2, 4, 6, 9, 3, 8, 11])
a[(a>=3)&(a<=8)] *= -1
print(a)

[ 2 -4 -6  9 -3 -8 11]


In [50]:
#14 Create [[0 1 2 3 4] 5 rows wo np.tile()
a = np.array([0,1,2,3,4])
np.broadcast_to(a,(5,5))
np.tile(a,(5,1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

np.broadcast_to(array,(rows,cols))
np.tile(array,(rows,times of repeat)))

In [33]:
#15 Subtract the mean of each row from every element in that row.
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a - np.mean(a, axis = 1, keepdims=True)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [51]:
#16 Create a random vector of 10 numbers and replace its maximum with 0.
a= np.random.rand(10)
a[np.argmax(a)] = 0
print(a)

[0.11752702 0.31419724 0.06816746 0.15148036 0.33806946 0.41793698
 0.82632173 0.39750063 0.         0.72607767]
